
(deftheme nyvis-night
  "dannyvis theme")

(custom-theme-set-faces
 'dannyvis-theme-night

 '(default ((t (:background "#131420" :foreground "#77757e"))))
 ;'(default ((t (:background "#181926" :foreground "#77757e"))))
 ;'(default ((t (:background "#1B1D2a" :foreground "#a7a5ae"))))
 '(cursor ((t (:foregound "#c89890"))))

 '(normal ((t (:weight normal))))
 '(bold-italic ((t (:weight normal ))))
 '(custom-face-tag ((t (:foreground "#88C9EE" :weight normal))))
 '(custom-state ((t (:foreground "#A6E22E"))))
 '(italic ((t ())))
 '(region ((t (:background "#101119"))))
 ;'(region ((t (:background "#403D3D"))))
 '(underline ((t (:underline t))))
 '(css-selector ((t (:foreground "#F92672"))))
 '(css-property ((t (:foreground "#88C9EE"))))
 '(diff-added ((t (:foreground "#A6E22E" :weight normal))))
 '(diff-context ((t (:foreground "#F8F8F2"))))
 '(diff-file-header ((t (:foreground "#88C9EE" :background nil))))
 '(diff-indicator-added ((t (:foreground "#A6E22E"))))
 '(diff-indicator-removed ((t (:foreground "#F92672"))))
 '(diff-header ((t (:foreground "#F8F8F2" :background "#232526"))))
 '(diff-hunk-header ((t (:foreground "#AE81FF" :background "#232526"))))
 '(diff-removed ((t (:foreground "#F92672" :weight normal))))
 '(escape-glyph ((t (:foreground "#FFFF33"))))
 '(minibuffer-prompt ((t (:foreground "#88C9EE"))))
 '(mode-line ((t (:foreground "#F8F8F2" :background "#000000"
                  :box (:line-width 1 :color "#000000" :style released-button)))))
 '(mode-line-buffer-id ((t (:foreground nil :background "#000000" :weight normal))))
 '(mode-line-inactive ((t (:foreground "#BCBCBC" :background "#000000"
                           ':box (:line-width 1 :color "#232526")))))
 '(mode-line-mousable ((t (:foreground "#BCBCBC" :background "#000000"))))
 '(mode-line-mousable-minor-mode ((t (:foreground "#BCBCBC" :background "#000000"))))
 '(font-lock-builtin-face ((t (:foreground "#368ACA"))))
 ;'(font-lock-builtin-face ((t (:foreground "#36922E"))))
 ;'(font-lock-builtin-face ((t (:foreground "#A6E22E"))))
 '(font-lock-comment-face ((t (:foreground "#2E2E58"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#302A44"))))
 '(font-lock-constant-face ((t (:foreground "#AE81FF"))))
 '(font-lock-doc-face ((t (:foreground "#FFFF33" ))))
; '(font-lock-function-name-face ((t (:foreground "#F92672" ))))
 '(font-lock-function-name-face ((t (:foreground "#F92672" :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "#656FB0"))))
 ;'(font-lock-keyword-face ((t (:foreground "#7899C8"))))
 ;'(font-lock-keyword-face ((t (:foreground "#48A9CF"))))
 '(font-lock-negation-char-face ((t (:foreground "F92622":weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#A6E22E"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal))))
 '(font-lock-string-face ((t (:foreground "#705362"))))
 '(font-lock-type-face ((t (:foreground "#88C9EE"))))
 '(font-lock-variable-name-face ((t (:foreground "#206332"))))
 ;'(font-lock-variable-name-face ((t (:foreground "#216c36"))))
 ;'(font-lock-variable-name-face ((t (:foreground "#216C36"))))
 ;'(font-lock-variable-name-face ((t (:foreground "#538C8A"))))
; '(font-lock-variable-name-face ((t (:foreground "#F92672"))))
 ;'(font-lock-warning-face ((t (:foreground "#FFFFFF" ':background "#333333"))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" ':background "#101119"))))
 '(fringe ((t (:background "#11121E"))))
 '(highlight ((t (:foreground "#000000" :background "#C4BE89"))))
 '(hl-line ((t (:background "#293739"))))

; '(rainbow-delimiters-depth-1-face (:foreground "#FFAAAA"))
; '(rainbow-delimiters-depth-2-face (:foreground "#FFCCAA"))
; '(rainbow-delimiters-depth-3-face (:foreground "#CCFFAA"))
; '(rainbow-delimiters-depth-4-face (:foreground "#AAFFAA"))
; '(rainbow-delimiters-depth-5-face (:foreground "#AAFFCC"))
; '(rainbow-delimiters-depth-6-face (:foreground "#AAFFFF"))
; '(rainbow-delimiters-depth-7-face (:foreground "#AACCFF"))
; '(rainbow-delimiters-depth-8-face (:foreground "#AAAAFF"))
; '(rainbow-delimiters-depth-9-face (:foreground "#CCAAFF"))
; '(rainbow-delimiters-unmatched-face (:foreground "#FF6666"))




 '(icompletep-choices ((t (:foreground "#F92672"))))
 '(icompletep-determined ((t (:foreground "#A6E22E"))))
 '(icompletep-keys ((t (:foreground "#F92672"))))
 '(icompletep-nb-candidates ((t (:foreground "#AE81FF"))))
 '(isearch ((t (:foreground "#C4BE89" :background "#76231E"))))
 '(isearch-fail ((t (:foreground "#FFFFFF" :background "#333333"))))
 '(lazy-highlight ((t (:foreground "#A8AEDF" :background "#225534"))))
 '(markdown-italic-face ((t ())))
 '(markdown-bold-face ((t (:weight normal))))
 '(markdown-header-face ((t (:weight normal))))
 '(markdown-header-face-1 ((t (:foreground "#88C9EE"))))
 '(markdown-header-face-2 ((t (:foreground "#F92672"))))
 '(markdown-header-face-3 ((t (:foreground "#A6E22E"))))
 '(markdown-header-face-4 ((t (:foreground "#AE81FF"))))
 '(markdown-header-face-5 ((t (:foreground "#FFFF33"))))
 '(markdown-header-face-6 ((t (:foreground "#88C9EE"))))
 '(markdown-inline-code-face ((t (:foreground "#88C9EE"))))
 '(markdown-list-face ((t (:foreground "#A6E22E"))))
 '(markdown-blockquote-face ((t ())))
 '(markdown-pre-face ((t (:foreground "#AE81FF"))))
 '(markdown-link-face ((t (:foreground "#88C9EE"))))
 '(markdown-reference-face ((t (:foreground "#88C9EE"))))
 '(markdown-url-face ((t (:foreground "#FFFF33"))))
 '(markdown-link-title-face ((t (:foreground "#F92672"))))
 '(markdown-comment-face ((t (:foreground "#461430"))))
 '(markdown-math-face ((t (:foreground "#AE81FF" ))))
 '(mumamo-background-chunk-major ((t (:background "#272822"))))
 '(mumamo-background-chunk-submode ((t (:background "#1B1D1E"))))
 '(outline-1 ((t (:foreground "#88C9EE"))))
 '(outline-2 ((t (:foreground "#F92672"))))
 '(outline-3 ((t (:foreground "#A6E22E"))))
 '(outline-4 ((t (:foreground "#AE81FF"))))
 '(outline-5 ((t (:foreground "#FFFF33"))))
 '(outline-6 ((t (:foreground "#88C9EE"))))
 '(outline-7 ((t (:foreground "#F92672"))))
 '(outline-8 ((t (:foreground "#A6E22E"))))
 '(secondary-selection ((t (:background "#272822"))))
 '(show-paren-match-face ((t (:foreground "#000000" :background "#FD971F"))))
 '(show-paren-mismatch-face ((t (:foreground "#960050" :background "#1E0010"))))
 '(widget-inactive-face ((t (:background "#ff0000"))))
 '(woman-addition ((t (:foreground "#AE81FF"))))
 '(woman-bold ((t (:foreground "#F92672"))))
 '(woman-italic ((t (:foreground "#A6E22E"))))
 '(woman-unknown ((t (:foreground "#88C9EE"))))

 '(font-lock-negation-char-face ((t nil)))
 '(highlight-symbol-face ((t (:background "#102115"))))
 '(linum ((t (:foreground "#30355A"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "RoyalBlue4"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#135523"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "plum4"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "MediumPurple4"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "maroon4"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "yellow3"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "OliveDrab3"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "turquoise3"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "DeepPink1"))))
 '(region ((t (:background "#102115"))))
 )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'dannyvis-theme-night)

;;; molokai-theme.el ends here

